relativeURLs = true
googleAnalytics = "UA-159072578-1"
title = "Raphaël Lafrogne-Joussier"
theme = "academimal"
sectionPagesMenu = "main"
defaultContentLanguage = "en"
disableKinds = ["taxonomy", "taxonomyTerm"]
baseURL = "https://raphael-lafrogne-joussier.github.io/"

[author]
name = "Raphaël Lafrogne-Joussier"

[params]
title = "Economist at the French Treasury"
institution = ""
logo = "RLJ_half_pic.jpeg"
Linkedin = "raphaël-lafrogne-joussier"
Twitter = "Raph_LaJouss"
Email = "r.lafrogne@gmail.com"

